export const GET_PAGE_DATA = 'adminMaintain/GET_PAGE_DATA';
export const SAVE_AUTH = 'adminMaintain/SAVE_AUTH';
export const SHOW_MODAL = 'adminMaintain/SHOW_MODAL';
export const HIDE_MODAL = 'adminMaintain/HIDE_MODAL';
export const GET_NAME = 'adminMaintain/GET_NAME';
export const SEARCH_RESULT = 'adminMaintain/SEARCH_RESULT';   //搜索結果
export const ORDER_DATA = 'adminMaintain/ORDER_DATA';     //单据内容
export const IS_AUTH = 'adminMaintain/IS_AUTH';   //权限判断
export const SEARCH_SELECT = 'adminMaintain/SEARCH_SELECT';
export const TRAVEL_AUTH = 'adminMaintain/TRAVEL_AUTH';
export const TRAVEL_SAVE_AUTH = 'adminMaintain/TRAVEL_SAVE_AUTH'; 
export const TRAVEL_ADD = 'adminMaintain/TRAVEL_ADD';
export const KM_MAINTAIN = 'adminMaintain/KM_MAINTAIN';
export const KM_FILE = 'adminMaintain/KM_FILE';
export const SHOW_KM_BTN = 'adminMaintain/SHOW_KM_BTN';
export const AIRLine_COMPANY_DATA = 'adminMaintain/AIRLine_COMPANY_DATA';
export const AIRLINE_COMPANY_ADD = 'adminMaintain/AIRLINE_COMPANY_ADD';
export const FLIGHT_TIME_DATA = 'adminMaintain/FLIGHT_TIME_DATA';
export const FLIGHT_TIME_FILE = 'adminMaintain/FLIGHT_TIME_FILE';